sparqlPoint: "http://localhost:7200/"
username: changeme
password: changeme

queryRoot: c:/data/query

server:
  requestLog:
    appenders:
      - type: file
        archive: false
        currentLogFilename: ./request.log

logging:
  level: INFO
  appenders:
    - type: file
      archive: false
      currentLogFilename: ./application.log
      
views:
    .ftl:
        template_exception_handler: rethrow
        output_encoding: utf-8